package by.khodokevich.web.command;

public enum CommandType {
    REGISTER,
    ACTIVATE,
    SIGN_IN,
    LOG_OUT,
    DEFAULT,
    SET_LOCALE,
    FIND_ORDERS_BY_SPECIALIZATIONS,
    FIND_MY_ORDERS,
    FIND_ORDER_INFO_DETAILS,
    ALL_ORDERS,
    CREATE_ORDER,
    ALL_EXECUTORS,
    FIND_EXECUTOR_INFO_DETAILS,
    ARCHIVED_ORDER,
    FIND_EXECUTORS_BY_SPECIALIZATIONS,

    GO_TO_MAIN,
    GO_TO_REGISTRATION,
    GO_TO_SIGN_IN,
    GO_TO_ERROR404,
    GO_TO_CREATION_ORDER_PAGE,

}
